# Site settings
title: Elie Génard
email: elaye.github.io@gmail.com
description: Creative coding and stuff...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://elaye.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  elaye
linkedin_username: elie-genard
vimeo_userid: user37359615
rss: true

# Build settings
markdown: kramdown

enable_tags: true
enable_comments: false

gems:
  - jekyll-sitemap
